name: .NET CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Build Project
        run: dotnet build --configuration Release

      - name: Run Test
        run: dotnet test --no-build --verbosity normal

      - name: Check Code Formatting
        run: dotnet format --severity warn
