name: .NET CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Build Project
        run: dotnet build --configuration Release
        working-directory: PROG6221_Part3_ST10440987

      - name: Run Test
        run: dotnet test PROG6221_FinalPoE_Part3/PROG6221_Part3_ST10440987 --no-build --verbosity normal

      - name: Check Code Formatting
        run: dotnet format --severity warn
